### ISSUE TITLE
Handle error in api/quiz/end/:quizCode

### ISSUE THREAD

**Issue by cynthiarich** [pub-trivia/trivia-app#131]
```post /api/quiz/end/:quizCode M6R4
[1] Executing (default): SELECT q.quizId, u.questionId, q.questionCount
[1]                             FROM quizzes q
[1]                             INNER JOIN QuizQuestionsAssoc u ON q.quizId = u.quizId
[1]                             WHERE q.quizCode="M6R4" AND q.isActive=1 AND u.questionOrder=1;
[1] Executing (default): UPDATE `quizzes` SET `isActive`=?,`updatedAt`=? WHERE `quizId` = ?
[1] get /api/quiz/scores/:quizCode for M6R4
[1] Executing (default): SELECT q.quizId, u.questionId, q.questionCount
[1]                             FROM quizzes q
[1]                             INNER JOIN QuizQuestionsAssoc u ON q.quizId = u.quizId
[1]                             WHERE q.quizCode="M6R4" AND q.isActive=1 AND u.questionOrder=1;
[1] (node:48647) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `quizId` of 'undefined' or 'null'.
[1]     at /Users/cynthiarich/Documents/UNC-BOOTCAMP/team-projects/trivia-app/routes/game-routes.js:190:15
[1] (node:48647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:48647) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] get /api/quiz/question/:quizCode M6R4
[1] Executing (default): SELECT q.quizId, u.questionId, u.questionOrder, q.questionCount
[1]                             FROM quizzes q
[1]                             INNER JOIN QuizQuestionsAssoc u ON q.quizId = u.quizId
[1]                             WHERE q.quizCode="M6R4" AND q.isActive=1 AND u.progress="started";
[1] (node:48647) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `questionId` of 'undefined' or 'null'.
[1]     at /Users/cynthiarich/Documents/UNC-BOOTCAMP/team-projects/trivia-app/routes/game-routes.js:101:15
[1] (node:48647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[1] get /api/quiz/scores/:quizCode for M6R4
[1] Executing (default): SELECT q.quizId, u.questionId, q.questionCount
[1]                             FROM quizzes q
[1]                             INNER JOIN QuizQuestionsAssoc u ON q.quizId = u.quizId
[1]                             WHERE q.quizCode="M6R4" AND q.isActive=1 AND u.questionOrder=1;
[1] (node:48647) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `quizId` of 'undefined' or 'null'.
[1]     at /Users/cynthiarich/Documents/UNC-BOOTCAMP/team-projects/trivia-app/routes/game-routes.js:190:15
[1] (node:48647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by cynthiarich** [comment]
This is fixed by #143 - closing this issue now!
